name: Check code

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Check code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Check build
        run: yarn build
